# Generated by Django 4.2.7 on 2023-11-12 05:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("post", "0002_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="created_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
